# Generated by Django 2.0 on 2017-12-21 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('author', models.CharField(blank=True, max_length=50)),
                ('type', models.IntegerField()),
                ('checkpoints', models.SmallIntegerField()),
                ('bonuses', models.SmallIntegerField()),
                ('difficulty', models.SmallIntegerField()),
                ('prevent_prehop', models.SmallIntegerField()),
                ('enable_baked_triggers', models.BooleanField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Spawn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zone', models.SmallIntegerField()),
                ('type', models.SmallIntegerField()),
                ('origin', models.CharField(max_length=80)),
                ('angle', models.CharField(max_length=80)),
                ('velocity', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.CharField(max_length=80)),
                ('end', models.CharField(max_length=80)),
                ('type', models.IntegerField()),
                ('value', models.IntegerField()),
                ('limit_speed', models.BooleanField()),
                ('target_name', models.CharField(blank=True, max_length=32)),
                ('filter_name', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MapConfiguration',
            fields=[
                ('map', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='maps.Map')),
                ('config', models.CharField(blank=True, max_length=20000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='zone',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Map'),
        ),
        migrations.AddField(
            model_name='spawn',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Map'),
        ),
        migrations.AlterUniqueTogether(
            name='spawn',
            unique_together={('map', 'zone', 'type')},
        ),
    ]
