# Generated by Django 2.0 on 2017-12-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='bonuses',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='checkpoints',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='difficulty',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='prevent_prehop',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='type',
            field=models.IntegerField(blank=True),
        ),
    ]
