# Generated by Django 2.0 on 2017-12-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20171230_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='active',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='map',
            name='author',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='map',
            name='bonuses',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='map',
            name='checkpoints',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='map',
            name='difficulty',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='map',
            name='enable_baked_triggers',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='map',
            name='prevent_prehop',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='map',
            name='type',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
