# Generated by Django 2.0 on 2018-03-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20171230_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='prevent_prehop',
            field=models.CharField(blank=True, choices=[('N', 'Disabled'), ('G', 'Global'), ('S', 'Stage Start'), ('F', 'First Stage Start')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='map',
            name='type',
            field=models.CharField(blank=True, choices=[('S', 'Staged'), ('L', 'Linear')], default='S', max_length=1),
        ),
    ]
