# Generated by Django 2.0 on 2017-12-21 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('steam_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('ip', models.CharField(blank=True, max_length=32)),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.Player')),
                ('hud_config', models.CharField(blank=True, max_length=30)),
                ('hide_panel', models.BooleanField()),
                ('sounds', models.BooleanField()),
                ('color_scheme', models.SmallIntegerField()),
                ('chat_mode', models.SmallIntegerField()),
                ('teleport_velocity', models.BooleanField()),
            ],
        ),
    ]
