# Generated by Django 2.0 on 2017-12-21 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='PlayerOption',
        ),
    ]
